### ISSUE TITLE
Ability to display/hide bank references and principal section per vendor

### ISSUE THREAD

**Issue by tbstevens** [TamarackConsulting/Creekridge_Portal#132] opened 2015-01-09 20:22 UTC
Enhancement Request:
--------------------------------
Creekridge would like the ability to display or hide the Bank Reference section and Principal section based on configuration for each site.

Solution:
-------------
1. New custom field on site with key name of "Include Bank References" with type of "True/False"
2. New custome field on site with key name of "Include Principals" with type of "True/False"
3. Add logic to Payment Calculator to not display the Bank Reference section if the current site's custom field of "Include Bank References" is explicitly set to "False". If true, null or empty string, display Bank References.
4. Add logic to Payment Calculator to not display the Principals section if the current site's custom field of "Include Principals" is explicitly set to "False". It true, null or empty string, display Principals.
5. If either field is set to false, the sections should not appear in view only or edit mode.

**Comment by tbstevens** [comment] 2015-01-13 06:10
@OlegForce - Let me know if you have any questions on this one.

**Comment by Creekridge** [comment] 2015-01-15 17:11
@tbstevens looks like these sections, even marked "true" to show on liferay aren't showing on site for Vendor 1.

**Comment by tbstevens** [comment] 2015-01-15 18:10
@Creekridge - Could you try this again? I just went out to vendorservicegroup.com and was able to flip them back and forth and it was working as expected with vendor1 with no changes made.

**Comment by Creekridge** [comment] 2015-01-16 17:52
Still not working correctly.  I set Include Bank to False and Include Principals to True, reclogged in as SalesManager and both sections showed up.  Tried switching both to False - both still showed up. Set both to false - both still showed up.

**Comment by tbstevens** [comment] 2015-01-16 20:14
@Creekridge - Ok - we have a much bigger issue taking place here with logging in and out from the browser as different user accounts which seems to be impacting the functionality of the page. I've tested the Hide/Display custom field settings 3 times now on vendorservicesgroup.com and it is working every time. Flipping it back and forth both ways. Then I login as a sales manager role, it displays correctly per the config. I log out and log back in as an admin, change the settings again, now broken. This is the same issue going on with filters so there is something bizarre going on across the board with logging in and out under different user profiles. I will look into this.

**Comment by tbstevens** [comment] 2015-01-19 17:57
@Creekridge - retested and working after fix.

**Comment by Creekridge** [comment] 2015-01-19 22:24
Only worked when logged in as admin.  Logged off, closed Internet Explorer, relogged in as salesreptester, and could still see Bank.

**Comment by tbstevens** [comment] 2015-01-20 15:44
@OlegForce - The hide/display Bank References and Principal feature appears to only be hiding and displaying these sections correctly for admins. When logged in under different roles, the sections are not hiding or displaying based on the configuration of the site.

**Comment by OlegForce** [comment] 2015-01-21 02:43
@psakia for some reason when logged in as a regular use, expandobridge is showing properties, but values are coming in as null... when logged in as admin user, everything is fine. What am I missing? 

Admin : 

expando:  {Rep Name=Oleg, Include Bank References=false, Rep Phone=703-889-0022, Vendor State=MN, Vendor Zip=42421, Include Principals=true, Vendor Phone=2131312312, Vendor Address=123 Street, Vendor City=City, Rep Email=dev+creekridgedev@sfdcdev.com}

rep: 

expando:  {Rep Name=null, Include Bank References=null, Rep Phone=null, Vendor State=null, Vendor Zip=null, Include Principals=null, Vendor Phone=null, Vendor Address=null, Vendor City=null, Rep Email=null}

**Comment by psakia** [comment] 2015-01-21 03:07
Hi Oleg, 
I will take a look and let you.
Thanks,
Pius

**Comment by tbstevens** [comment] 2015-01-21 20:25
@Creekridge - Custom Field permissions updates resolved the issue. Tested in prod by logging in as an admin in another separate browser session and as a sales rep in another browser session. Had the sales rep on a view only application screen and edit application screen. Had the admin user in the other browser toggling the bank ref and principal sections between true and false. Refreshing the sales rep screens correctly displayed or hid the sections.

**Comment by Creekridge** [comment] 2015-01-23 21:13
Confirmed it works.

**Closed** 2015-01-23 22:05 UTC
Labels: Ready for Testing
