### ISSUE TITLE
Add functionality to support multiple templates

### ISSUE THREAD

**Issue by kdolan12** [TamarackConsulting/Creekridge_Portal#156] opened 2015-01-16 17:10 UTC
1) We will allow any number of templates to be created; not just proposal and quote letters.
2) We will update the logic so that the fields specified as tags on the document reflect the database column names.  (In Properties file for max flexibility)
3) We will add two fields to the Custom Fields screen under Site settings that will allow you to configure the list of document templates for a given vendor:
>a. Vendor Template HTML Files
>>i.semi colon delimited list of html file names to use for this vendor.

>b. Vendor Template Titles
>>i.semi colon delimited list of Template titles
ii.Must be aligned with the comma delimited list of html files in the field above.
iii.Title will be displayed in the Manage Documents page to inform users which templates are available for generation

4) For the Bank References and Principals, we would need to have separate HTML documents for each of these that get merged into the main HTML template.  
5) We would add one additional button to the Manage Documents page called “Generate Selected Documents” where all documents listed in the vendor setup would be created.  We would remove 2 buttons for Generate Proposal & Quote Letter.  We would now just have a list of document titles with checkboxes for which documents should be generated.
6) There are 2 new custom fields on the prod server for each site. Key names are “Hide Bank Refrences” and “Hide Principals”. 
>a. If "Hide Bank References" = FALSE for the group/site when generating the doc, the doc should not display the Bank References section.
b. If "Hide Principals" = FALSE for the group/site when generating the doc, the doc should not display the Principals section.
c. In addition, if either of those sections are = TRUE but the record count = 0, do not display those sections in the document.

**Comment by divinami** [comment] 2015-01-18 01:32
@kdolan12 @tbstevens All of the changes are done except for Item #5 which I'm reassigning to @OlegForce to implement.  Both links just generate all of the documents for now.  Please test it out and let me know if anything needs to be changed.  Some notes on the implementation:

>> Any tag that starts with @ means that it will parse in that HTML for multi row objects (i.e. [@CreditAppTemplate_Principals1.html]).

>> For hiding the Principals and Bank References sections, the following strings are required in the HTML templates to indicate where each section begins and ends -





>> The table name for user tags is "User_".

>> The vendor tags match the names of the custom fields added.  No table name is required.

**Comment by divinami** [comment] 2015-01-18 01:38
@OlegForce Assigning this to you to work on Item #5.  Will just need a list of HTML document templates that are checked off to generate and send the list to ManageDocumentUtil.generateDocument().  It can just be a semicolon delimited string.  Let me know if you have any questions.  Thanks.

**Comment by kdolan12** [comment] 2015-01-18 17:13
@OlegForce let me know if you want to discuss.  I can walk you through functionally what we're trying to accomplish here.

**Comment by tbstevens** [comment] 2015-01-21 07:39
@Creekridge - The new Manage Docs capabilities have been deployed to production. I won't go into great detail in this comment as it is probably better served through a call, but in Vendor1 you'll notice that it is setup with the default Credit Application and Proposal Letter templates and both can be generated by checking them and clicking the Generate Selected Documents button. You should also notice a significant improvement on the speed in which the docs are generated.

**Comment by Creekridge** [comment] 2015-01-21 17:29
See checkboxes and Generate Docs button, but both documents generate when only 1 selected.  Speed is much faster.

**Comment by tbstevens** [comment] 2015-01-21 18:38
@OlegForce  - Looks like we need to make a fix to ensure only the selected documents are generated. If you only check one of the options it is generating both docs, per creekridge's message above.

**Comment by OlegForce** [comment] 2015-01-22 00:59
ok. It should work now.

**Comment by tbstevens** [comment] 2015-01-22 05:03
@Creekridge - Tested in prod. As mentioned in the comment above, you can use vendor1 to test the message with Rep Name and Rep Phone configured. Vendor2 currently displays the message if Rep Name and Rep Phone are not configured.

**Comment by Creekridge** [comment] 2015-01-23 21:09
@tbstevens think your last comment was on the wrong case.  Confirmed I can generate the documents separately.

**Closed** 2015-01-23 22:04 UTC
Labels: Ready for Testing
