### ISSUE TITLE
Guest Users

### ISSUE THREAD

**Issue by Creekridge** [TamarackConsulting/Creekridge_Portal#193] opened 2015-02-27 22:40 UTC
@tbstevens we have it set up so guest users can join. The only thing we noticed is that when a new user is joining, there is a message that states that the initial password is emailed to them....and no email is actually sent. Any way to fix this?

**Comment by tbstevens** [comment] 2015-02-28 18:21
@Creekridge - I tested out all other types of email. It appears to have stopped working across the board. I'm not sure when this occurred. My suspicion is based on one of the prod environment changes (dmz, domain, ssl) but I'm not sure when it stopped working. Do you happen to have an email from testing that would give us a good idea of when the emails stopped working?

Here's the error from the log.

12:08:46,012 ERROR [http-bio-8443-exec-177][MailEngine:132] null

javax.mail.MessagingException: Could not connect to SMTP host: 192.168.0.9, port: 25, response: 421

	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1270)

	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:370)

	at javax.mail.Service.connect(Service.java:275)

	at com.liferay.util.mail.MailEngine._send(MailEngine.java:538)

	at com.liferay.util.mail.MailEngine.send(MailEngine.java:356)

	at com.liferay.util.mail.MailEngine.send(MailEngine.java:167)

	at com.liferay.util.mail.MailEngine.send(MailEngine.java:385)

	at com.liferay.util.mail.MailEngine.send(MailEngine.java:132)

	at com.liferay.util.mail.MailEngine.send(MailEngine.java:438)

**Comment by kdolan12** [comment] 2015-02-28 18:27
@Creekridge can you verify the IP for the mail server?  192.168.0.9 looks like an dynamic IP address for the machine.

to SMTP host: 192.168.0.9, port: 25, response: 421

**Comment by tbstevens** [comment] 2015-02-28 19:00
@Creekridge @kdolan12 - Looking back on the original email it looks like the current smtp we are using is for internal. When we tried to setup the owa.leaseaccess.info/exchange smtp it didn't work and we set it up with the internal ip. I tried adjusting the settings to change the smtp to "owa.leaseaccess.info/exchange" but it is still not working.

**Comment by tbstevens** [comment] 2015-02-28 19:13
@Creekridge - Could you confirm if "owa.leaseaccess.info/exchange" is the actual smtp we need?

I tried logging into https://owa.leaseaccess.info/owa with the same credentials provided to see if I could get/verify the smtp (https://support.office.com/en-au/article/Settings-for-POP-and-IMAP-access-for-Office-365-for-business-or-Microsoft-Exchange-accounts-7fc677eb-2491-4cbc-8153-8e7113525f6c) but I was unable to login with the current credentials originally provided. Tried a variation of usernames -- portal, portal@vendorservicesgroup.com, portal@leaseaccess.info but was unable to login.

If we can get a confirmed smtp, user, and pass I'll see if adjusting the settings will work.

Thanks!

**Comment by Creekridge** [comment] 2015-02-28 19:41
Where are the email settings in Liferay?  There are a few options I'd like to try,

Sandy

On Feb 28, 2015, at 1:13 PM, tbstevens <notifications@github.com<mailto:notifications@github.com>> wrote:


@Creekridge<https://github.com/Creekridge> - Could you confirm if "owa.leaseaccess.info/exchange" is the actual smtp we need?

I tried logging into https://owa.leaseaccess.info/owa with the same credentials provided to see if I could get/verify the smtp (https://support.office.com/en-au/article/Settings-for-POP-and-IMAP-access-for-Office-365-for-business-or-Microsoft-Exchange-accounts-7fc677eb-2491-4cbc-8153-8e7113525f6c) but I was unable to login with the current credentials originally provided. Tried a variation of usernames -- portal, portal@vendorservicesgroup.com<mailto:portal@vendorservicesgroup.com>, portal@leaseaccess.info<mailto:portal@leaseaccess.info> but was unable to login.

If we can get a confirmed smtp, user, and pass I'll see if adjusting the settings will work.

Thanks!

**Comment by Creekridge** [comment] 2015-02-28 19:45
It isn't a dynamic IP....it's an assigned and reserved IP.

Sent from my iPad

On Feb 28, 2015, at 12:27 PM, Kristian Dolan <notifications@github.com<mailto:notifications@github.com>> wrote:


@Creekridge<https://github.com/Creekridge> can you verify the IP for the mail server? 192.168.0.9 looks like an dynamic IP address for the machine.

to SMTP host: 192.168.0.9, port: 25, response: 421

**Comment by tbstevens** [comment] 2015-02-28 20:36
@creekridge - email settings are at admin>control panel > configuration > server administration > mail

Its the outbound settings if you scroll below the inbound settings.

**Comment by Creekridge** [comment] 2015-02-28 21:56
@tbstevens - made some changes to the server and my email server and it's working now.

**Comment by tbstevens** [comment] 2015-02-28 23:36
@creekridge - great to hear. I'll go ahead and close this one out. Thanks Sandy.

**Closed** 2015-02-28 23:36 UTC
Labels: Major Defect
